name: CI against Hedera Services master branch

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Hedera Services
        uses: actions/checkout@v2
        with:
          repository: hashgraph/hedera-services
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Hedera Services locally
        run: |
          git tag MASTER
          echo "TAG=MASTER" >> .env
          docker build -t services-node:HEDERA_SDK_TEST .
          docker-compuse up &
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Build Hedera SDK with JDK 14
        run: ./gradlew build

